--Exo1:
CREATE DATABASE languages;

--Exo2:
CREATE DATABASE webDeveolopment CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

--Exo3:
CREATE DATABASE IF NOT EXISTS frameworks CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

--Exo4:
CREATE DATABASE IF NOT EXISTS languages CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

--Exo5:
DROP DATABASE languages;

--Exo6:
DROP DATABASE IF EXISTS frameworks;

--Exo7:
DROP DATABASE IF EXISTS languages;
